
name = "DashHtmlComponents"
uuid = "1b08a953-4be3-4667-9a23-e4a2b8b6b400"
authors = ["Chris Parmer <chris@plot.ly>"]
version = "1.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compact]
julia = "1.1"
Dash = ">=0.1"
