
name = "DashHtmlComponents"
uuid = "1b08a953-4be3-4667-9a23-341813c6f7a5"
authors = ["Chris Parmer <chris@plot.ly>"]
version = "1.0.1"

[deps]
DashBase = "03207cf0-e2b3-4b91-9ca8-690cf0fb507e"

[compact]
julia = "1.2"
DashBase = ">=0.1"
